import '../styles/globals.css';
import { Provider } from 'react-redux';
import store from '../store';
import * as React from 'react';
import Header from './layout/Header';
import Head from 'next/head';
function MyApp({ Component, pageProps }) {
  return (
  <Provider store={store}>
    <Head>
      <title>Blog</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-5003930059909941" crossOrigin="anonymous"></script>
      <script src="https://unpkg.com/react/umd/react.production.min.js" crossorigin></script>
      <script src="https://unpkg.com/react-dom/umd/react-dom.production.min.js" crossorigin></script>
      <script src="https://unpkg.com/react-bootstrap@next/dist/react-bootstrap.min.js" crossorigin></script>
    </Head>
      <div style={{backgroundColor: '#edf2f7'}}>
        <Header />
        <main>
          <Component {...pageProps} />
        </main>
      </div>
    </Provider>
  )
}

export default MyApp
