import '../styles/globals.css';
import { Provider } from 'react-redux';
import store from '../store';
import * as React from 'react';
import Header from './layout/Header';
import Navigation from './layout/Navigation';
import Head from 'next/head';
import Script from 'next/Script';

function MyApp({ Component, pageProps }) {

  return (
  <Provider store={store}>
    <Head>
      <title>Blog</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <Script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-5003930059909941" crossOrigin="anonymous"></Script>
    </Head>
      <div style={{backgroundColor: '#edf2f7'}}>
        <Header />
        <Navigation />
        <main>
          <Component {...pageProps} />
        </main>
      </div>
    </Provider>
  )
};

export default MyApp
