import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useWindowSize } from 'react-use';
import { useEffect } from 'react';
import store from '../store'
import Footer from './components/Footer'
import Card from './components/Card'

export default function Home() {
  // https://gray-code.com/javascript/property-and-method-and-event-list-of-audioelement-and-videoelement/
{/* <fieldset>
  <legend>Equalizer</legend>
  
  <label orient='270deg' type='range' for="band" before="-5" after="5">0</label>
  
  <input orient='270deg' type='range' min='0' value='2' max='9' step='1' />
  <input orient='270deg' type='range' min='0' value='2' max='9' step='1' />
  <input orient='270deg' type='range' min='0' value='2' max='9' step='1' />
  <input orient='270deg' type='range' min='0' value='4' max='9' step='1' />
  <input orient='270deg' type='range' min='0' value='3' max='9' step='1' />
  <input orient='270deg' type='range' min='0' value='3' max='9' step='1' />
  <input orient='270deg' type='range' min='0' value='6' max='9' step='1' />
  <input orient='270deg' type='range' min='0' value='7' max='9' step='1' />
  <input orient='270deg' type='range' min='0' value='7' max='9' step='1' />
  <input orient='270deg' type='range' min='0' value='8' max='9' step='1' />
  <input orient='270deg' type='range' min='0' value='8' max='9' step='1' />
  <input orient='270deg' type='range' min='0' value='6' max='9' step='1' />
  <input orient='270deg' type='range' min='0' value='5' max='9' step='1' />
  <input orient='270deg' type='range' min='0' value='6' max='9' step='1' />
  <input orient='270deg' type='range' min='0' value='6' max='9' step='1' />

  <label orient='90deg' type='range' for="band" before="5" after="-5">0</label>

</fieldset> */}
  const { width, height } = useWindowSize();
  let dummyCards = []
  useEffect(() => {
    let dummyCardsNum = 0;
    if(width > 1159) dummyCardsNum = 4;
    else if(width > 1059) dummyCardsNum = 3;
    else if(width > 726) dummyCardsNum = 2;
    else return;
    const cardNum = store.getState().audio.music.length % dummyCardsNum;
    for (let i = 0; i < dummyCardsNum - cardNum; i++) {
      dummyCards.push(<Card />)
    }
  }, [width, height]);
  const state = store.getState();
  return (
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <div style={{display: 'flex', flexWrap: 'wrap', justifyContent: 'center'}}>
            {
              state.audio.music.map(song => <Card key={song.id} {...song} />)
            }
            {dummyCards.map(card => card)}
          </div>
        </main>

        <Footer />
      </div>
  )
}

